<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Lanot
 * @package     Lanot_PremiumSticker
 * @copyright   Copyright (c) 2012 Lanot
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var $this Mage_Core_Model_Resource_Setup */
/** @var $helper Lanot_PremiumSticker_Helper_Data */
$helper = Mage::helper('lanot_premiumsticker');

//tables definition
$premiumStickerTable = $this->getTable('lanot_premiumsticker/sticker');
$easyStickerTable = $this->getTable('lanot_easysticker/sticker');

$premiumStickerProductTable = $this->getTable('lanot_premiumsticker/sticker_product');
$easyStickerProductTable = $this->getTable('lanot_easysticker/sticker_product');

$productTable = $this->getTable('catalog/product');
$websiteTable = $this->getTable('core/website');
$customerGroupTable = $this->getTable('customer/customer_group');

$this->startSetup();

//create table for sticker
$this->run("
	DROP TABLE IF EXISTS `{$premiumStickerTable}`;
	CREATE TABLE `{$premiumStickerTable}` (
	    `sticker_id`   int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Sticker ID',
	    `is_active`  tinyint DEFAULT 0,
	    `title`      varchar(255) DEFAULT NULL,
        `image`      varchar(255) DEFAULT NULL,
        `position`   varchar(32),

        `from_date` date DEFAULT NULL COMMENT 'From Date',
        `to_date` date DEFAULT NULL COMMENT 'To Date',
        `customer_group_ids` text COMMENT 'Customer Group Ids',
        `conditions_serialized` mediumtext COMMENT 'Conditions Serialized',
        `website_ids` text COMMENT 'Website Ids',

		`created_at` timestamp NULL DEFAULT NULL COMMENT 'Creation Time',
  		`updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update Time',

		PRIMARY KEY (`sticker_id`),		
		KEY `IDX_LNTPRMSTKR_IS_ACTIVE_TO_DATE_FROM_DATE` (`is_active`, `to_date`, `from_date`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Stickers Entity Table';
");

//create new columns
foreach ($helper->getAttributes() as $attributeCode) {
    $col = 'scale_' . $attributeCode;
    $this->run("ALTER TABLE `{$premiumStickerTable}` ADD `$col` SMALLINT DEFAULT NULL AFTER `position`");
}

//create table for sticker
$this->run("
	DROP TABLE IF EXISTS `{$premiumStickerProductTable}`;
	CREATE TABLE `{$premiumStickerProductTable}` (
	    `product_id`   int(10) unsigned NOT NULL COMMENT 'Product ID',
	    `sticker_id`   int(10) unsigned NOT NULL COMMENT 'Sticker ID',

        `from_time` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'From Time',
        `to_time` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'To time',
        `customer_group_id` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT 'Customer Group Id',
        `website_id` smallint(5) unsigned NOT NULL COMMENT 'Website Id',
        `auto` smallint(1) unsigned NOT NULL DEFAULT 0 COMMENT 'Is Auto Generated By Conditions',

        UNIQUE KEY `UNQ_PRMSTKR_PRODUCT` (`product_id`, `from_time`, `to_time`, `website_id`, `customer_group_id`, `sticker_id`, `auto`),

        KEY `IDX_PRMSTKR_PRODUCT_PRODUCT_ID` (`product_id`),
        KEY `IDX_PRMSTKR_PRODUCT_CUSTOMER_GROUP_ID` (`customer_group_id`),
        KEY `IDX_PRMSTKR_PRODUCT_WEBSITE_ID` (`website_id`),
        KEY `IDX_PRMSTKR_PRODUCT_FROM_TIME` (`from_time`),
        KEY `IDX_PRMSTKR_PRODUCT_TO_TIME` (`to_time`),
        KEY `IDX_PRMSTKR_PRODUCT_STICKER_ID` (`sticker_id`),
        KEY `IDX_PRMSTKR_PRODUCT_AUTO` (`auto`),

  		CONSTRAINT `FK_PRMSTICKER_PRODUCT_ID_CATALOG_PRODUCT_ENTITY_ID` FOREIGN KEY (`product_id`) REFERENCES `{$productTable}` (`entity_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  		CONSTRAINT `FK_PRMSTICKER_STICKER_ID_STICKER_STICKER_ID` FOREIGN KEY (`sticker_id`) REFERENCES `{$premiumStickerTable}` (`sticker_id`) ON DELETE CASCADE ON UPDATE CASCADE,
        CONSTRAINT `FK_PRMSTKR_PRODUCT_WEBSITE_ID_CORE_WEBSITE_WEBSITE_ID` FOREIGN KEY (`website_id`) REFERENCES `{$websiteTable}` (`website_id`) ON DELETE CASCADE ON UPDATE CASCADE,
        CONSTRAINT `FK_PRMSTKR_PRD_CSTR_GROUP_ID_CSTR_GROUP_GROUP_ID` FOREIGN KEY (`customer_group_id`) REFERENCES `{$customerGroupTable}` (`customer_group_id`) ON DELETE CASCADE ON UPDATE CASCADE
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Premium Stickers To Products Table';
");

$this->endSetup();
